import { Secular_One } from 'next/font/google';
import { Inter } from 'next/font/google';
import "./globals.css";

const secularOne = Secular_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-secular-one',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: "Carbon Compass",
  description: "Generated by Carbon Compass",
  icons: {
    icon: '/icon.png',
    shortcut: '/favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${secularOne.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
