import { Secular_One } from 'next/font/google';
import "./globals.css";

const secularOne = Secular_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-secular-one',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${secularOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
